### ISSUE TITLE
Using this inside a Docker container

### ISSUE THREAD

**Issue by MahbbRah** [Schmavery/facebook-chat-api#795]
Hi guys, Recently I'm trying to use this inside a docker container but getting erros like below. 

`error: connect econnrefused 157.240.7.35:443`

I'm exposing port `4000` from node-express application for my API. 

# Below is docker-compose yml file
```
version : '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: node_pa
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  node_backend:
    container_name: node_with_pa_msql
    build: ./backend_app
    environment:
      MYSQL_PORT: 3306
      PORT: 4006
      MYSQL_USER: root
      MYSQL_PW: root
      NODE_ENV: development
      MYSQL_HOST: mysql
      DATABASE_NAME: messenger_app_backend
      WAIT_HOSTS: mysql:3306
    # volumes: 
    #   - ./backend_app:/usr/src/app
    links:
      - mysql
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - 4000:4006
  mysql:
    image: mysql:5.6
    container_name: node_mysql
    volumes:
      - ./backend_app/db_sample:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: messenger_app_backend
```

# Dockerfile
```
FROM node:latest

# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
COPY . .

EXPOSE 8080

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && npm start
```
